[lintspec]
paths = []        # paths to files and folders to analyze
exclude = []      # paths to files or folders to exclude, see also `.nsignore`
inheritdoc = true # enforce that all overridden, public and external items have `@inheritdoc`

[output]
out = ""        # if provided, redirects output to this file
json = false    # output diagnostics as JSON
compact = false # compact output (minified JSON or compact text)
sort = false    # sort results by file path

[constructor]
notice = "ignore"
dev = "ignore"
param = "ignore"

[enum]
notice = "ignore"
dev = "ignore"
param = "ignore"

[error]
notice = "ignore"
dev = "ignore"
param = "require"
