[lintspec]
paths = []            # paths to files and folders to analyze
exclude = []          # paths to files or folders to exclude, see also `.nsignore`
inheritdoc = true     # enforce that all overridden, public and external items have `@inheritdoc`
notice_or_dev = false # do not distinguish between `@notice` and `@dev` when considering "required" validation rules

[output]
out = ""        # if provided, redirects output to this file
json = false    # output diagnostics as JSON
compact = false # compact output (minified JSON or compact text)
sort = false    # sort results by file path

[constructor]
notice = "ignored"
dev = "ignored"
param = "required"

[enum]
notice = "required"
dev = "ignored"
param = "ignored"

[error]
notice = "required"
dev = "ignored"
param = "required"

[event]
notice = "required"
dev = "ignored"
param = "required"

[function.private]
notice = "required"
dev = "ignored"
param = "required"
return = "required"

[function.internal]
notice = "required"
dev = "ignored"
param = "required"
return = "required"

[function.public]
notice = "required"
dev = "ignored"
param = "required"
return = "required"

[function.external]
notice = "required"
dev = "ignored"
param = "required"
return = "required"

[modifier]
notice = "required"
dev = "ignored"
param = "required"

[struct]
notice = "required"
dev = "ignored"
param = "ignored"

[variable.private]
notice = "required"
dev = "ignored"

[variable.internal]
notice = "required"
dev = "ignored"

[variable.public]
notice = "required"
dev = "ignored"
return = "required"
