paths = []            # paths to files and folders to analyze
exclude = []          # paths to files or folders to exclude, see also `.nsignore`
out = ""              # if provided, redirects output to this file
inheritdoc = true     # enforce that all overridden, public and external items have `@inheritdoc`
constructor = false   # enforce that constructors have natspec
struct_params = false # enforce that structs have `@param` for each member
enum_params = false   # enforce that enums have `@param` for each variant
# enforce NatSpec on items even if they don't have params/returns/members
enforce = ["variable", "struct"]
json = false                     # output diagnostics as JSON
compact = false                  # compact output (minified JSON or compact text)
sort = false                     # sort results by file path
